import os
import re
import xml.etree.ElementTree as ET
from pathlib import Path
from datetime import datetime
import sys

def parse_toml_dependencies(cargo_toml_path):
    with open(cargo_toml_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # We only care about internal references (path dependencies)
    deps = []
    # Regex to find: name = { path = "..." }  or name = { workspace = true }
    # Simplified approach: extracting names from [dependencies] block might be complex with regex.
    # We will rely on searching for workspace paths or simple path matches.
    for line in content.split('\n'):
        line = line.strip()
        if 'path = ' in line and not line.startswith('#'):
            match = re.search(r'^([a-zA-Z0-9_-]+)\s*=', line)
            if match:
                deps.append(match.group(1))
        # Handle simple workspace dependencies (name = { workspace = true })
        if 'workspace = true' in line and not line.startswith('#'):
            match = re.search(r'^([a-zA-Z0-9_-]+)\s*=', line)
            if match:
                deps.append(match.group(1))
    return deps

def get_crate_info(cargo_toml_path):
    name = "unknown"
    desc = "No description"
    if not cargo_toml_path.exists():
         return name, desc
    
    with open(cargo_toml_path, 'r', encoding='utf-8') as f:
        for line in f:
            if line.startswith('name ='):
                name = line.split('=')[1].strip().strip('"')
            elif line.startswith('description ='):
                desc = line.split('=')[1].strip().strip('"')
                break # got both
    return name, desc

def extract_env_vars():
    env_file = Path(".env.example")
    vars = []
    if env_file.exists():
        with open(env_file, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    key = line.split('=')[0]
                    vars.append(key)
    return vars

def generate_architecture():
    base_dir = Path(".")
    arch_file = base_dir / "ARCHITECTURE.md"
    
    # Check for manual sections
    manual_content_paradigm = ""
    manual_content_flow = ""
    
    if arch_file.exists():
        with open(arch_file, 'r', encoding='utf-8') as f:
            content = f.read()
            # Extract paradigm
            m1 = re.search(r'<!-- MANUAL_PARADIGM_START -->(.*?)<!-- MANUAL_PARADIGM_END -->', content, re.DOTALL)
            if m1: manual_content_paradigm = m1.group(1).strip()
            
            # Extract data flow
            m2 = re.search(r'<!-- MANUAL_FLOW_START -->(.*?)<!-- MANUAL_FLOW_END -->', content, re.DOTALL)
            if m2: manual_content_flow = m2.group(1).strip()
            
    if not manual_content_paradigm:
        manual_content_paradigm = "- **Pattern B Architecture**: Front-end uses Gemini Cloud (`gemini-2.5-flash`), Background tasks use Ollama Local (`qwen3.5:9b`).\n- **Abyss Vault**: Physical isolation of API keys in `key-proxy` process. Main AI engine holds no keys.\n- **WASM/Docker Sandboxing**: Strict isolation for executing dynamic AI skills."

    if not manual_content_flow:
        manual_content_flow = "1. **User Interaction**: User inputs prompt in Management Console (Tauri/React).\n2. **Routing**: `api-server` receives request, verifies auth.\n3. **LLM Chain**: Context Engine injects UI state & KIs -> Request sent to LLM.\n4. **Background**: `watchtower` loop runs every 5 mins, processes async skills via JobQueue."

    # Analyze workspace
    crates = {}
    
    root_cargo = base_dir / "Cargo.toml"
    with open(root_cargo, 'r', encoding='utf-8') as f:
        root_content = f.read()
    
    # Extract members
    members = []
    in_members = False
    for line in root_content.split('\n'):
        if line.startswith('members = ['):
            in_members = True
            mems = re.findall(r'"([^"]+)"', line)
            members.extend(mems)
            if ']' in line:
                in_members = False
        elif in_members:
            mems = re.findall(r'"([^"]+)"', line)
            members.extend(mems)
            if ']' in line:
                in_members = False

    for member_path in members:
        p = base_dir / member_path / "Cargo.toml"
        name, desc = get_crate_info(p)
        deps = parse_toml_dependencies(p)
        crates[name] = {
            'path': member_path,
            'desc': desc,
            'deps': deps
        }
        
    # Generate Output
    out = "# 📐 Aiome Architecture Map (AI-First)\n\n"
    out += "> This file is automatically generated by `scripts/generate_architecture.py` to provide a concise project structure overview for AI agents.\n\n"
    
    out += "## 1. Core Paradigms\n"
    out += "<!-- MANUAL_PARADIGM_START -->\n"
    out += manual_content_paradigm + "\n"
    out += "<!-- MANUAL_PARADIGM_END -->\n\n"

    out += "## 2. Key Data Flow\n"
    out += "<!-- MANUAL_FLOW_START -->\n"
    out += manual_content_flow + "\n"
    out += "<!-- MANUAL_FLOW_END -->\n\n"

    out += "## 3. System Topology (Internal Dependencies)\n\n"
    out += "```mermaid\n"
    out += "graph TD\n"
    
    # Add nodes (group by apps vs libs)
    out += "    subgraph Apps\n"
    for name, info in crates.items():
        if info['path'].startswith('apps/'):
            out += f"        {name}[{name}]\n"
    out += "    end\n\n"
    
    out += "    subgraph Libs\n"
    for name, info in crates.items():
        if info['path'].startswith('libs/'):
            out += f"        {name}({name})\n"
    out += "    end\n\n"

    # Add edges
    for name, info in crates.items():
        for dep in info['deps']:
            if dep in crates: # Only internal edges
                out += f"    {name} --> {dep}\n"
    out += "```\n\n"
    
    out += "## 4. Directory Map (Crates)\n\n"
    out += "| Crate | Path | Description |\n"
    out += "|---|---|---|\n"
    for name, info in crates.items():
        desc = info['desc'] if info['desc'] != 'No description' else '(Core Module)'
        out += f"| `{name}` | `{info['path']}` | {desc} |\n"
    out += "\n"
    
    out += "## 5. Critical Environment Variables\n"
    out += "*(Auto-extracted from `.env.example`)*\n"
    env_vars = extract_env_vars()
    if env_vars:
        out += "```text\n"
        out += ", ".join(env_vars) + "\n"
        out += "```\n\n"
        
    out += "---\n"
    out += f"*Last Auto-Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}*\n"

    with open(arch_file, 'w', encoding='utf-8') as f:
        f.write(out)

    print("✅ ARCHITECTURE.md successfully generated/updated.")

if __name__ == "__main__":
    generate_architecture()
