/*
 * Aiome - The Autonomous AI Operating System
 * Copyright (C) 2026 motivationstudio, LLC
 * 
 * Licensed under the Elastic License 2.0 (ELv2).
 * You may not provide the software to third parties as a hosted or managed service, 
 * where the service provides users with access to any substantial set of the features 
 * or functionality of the software.
 */

//! # TrendSonar — トレンド収集ツール (External Search API Integration)
//!
//! 定時でトレンドキーワードを取得する。
//! 外部への通信はすべて reqwest で行い、HTML/URLの除去等の検疫処理（Context Sanitization）を実施する。

use async_trait::async_trait;
use aiome_core::contracts::{TrendRequest, TrendResponse};
use aiome_core::error::AiomeError;
use aiome_core::traits::{AgentAct, TrendItem, TrendSource};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use regex::Regex;

/// Responses from External Web Search API
#[derive(Deserialize, Debug)]
struct WebSearchResponse {
    web: Option<WebWebResults>,
}

#[derive(Deserialize, Debug)]
struct WebWebResults {
    results: Vec<WebResultItem>,
}

#[derive(Deserialize, Debug)]
struct WebResultItem {
    description: Option<String>,
}

#[derive(Clone)]
pub struct ExternalTrendSonar {
    api_key: String,
    client: reqwest::Client,
}

impl ExternalTrendSonar {
    pub fn new(api_key: String) -> Self {
        Self {
            api_key,
            client: reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(10))
                .build()
                .unwrap_or_else(|_| reqwest::Client::new()),
        }
    }

    /// Context Sanitization: strips HTML tags, excessive whitespace, and URLs
    fn sanitize_snippet(snippet: &str) -> String {
        let mut text = snippet.to_string();
        
        // Strip URLs
        let url_re = Regex::new(r"https?://\S+").unwrap();
        text = url_re.replace_all(&text, "").to_string();
        
        // Strip HTML Tags
        let html_re = Regex::new(r"<[^>]+>").unwrap();
        text = html_re.replace_all(&text, "").to_string();
        
        // Clean up HTML Entities (basic ones)
        text = text.replace("&quot;", "\"")
                   .replace("&amp;", "&")
                   .replace("&lt;", "<")
                   .replace("&gt;", ">")
                   .replace("&#39;", "'");
                   
        // Collapse whitespace
        let ws_re = Regex::new(r"\s+").unwrap();
        text = ws_re.replace_all(&text, " ").to_string();
        
        text.trim().to_string()
    }
}

#[async_trait]
impl TrendSource for ExternalTrendSonar {
    async fn get_trends(&self, category: &str) -> Result<Vec<TrendItem>, AiomeError> {
        // Here `category` maps to the actual search query generated by Phase 1 (The Sonar Ping).
        tracing::debug!("ExternalTrendSonar: Fetching trends for query '{}'...", category);

        // API-Level Freshness: freshness=pd (Past 24 hours), count=3 to limit noise.
        let endpoint = std::env::var("SEARCH_API_ENDPOINT")
            .unwrap_or_else(|_| "https://api.search.provider.com/res/v1/web/search".to_string());
        
        let res = self.client.get(&endpoint)
            .query(&[("q", category), ("freshness", "pd"), ("count", "3")])
            .header("X-Subscription-Token", &self.api_key)
            .header("Accept", "application/json")
            .send()
            .await
            .map_err(|e| AiomeError::Infrastructure { reason: format!("External Search API request failed: {}", e) })?;

        if !res.status().is_success() {
            let status = res.status();
            let body = res.text().await.unwrap_or_default();
            tracing::error!("External Search API Error [{}]: {}", status, body);
            return Err(AiomeError::Infrastructure { reason: format!("External Search API error [{}]: {}", status, body) });
        }

        let search_res: WebSearchResponse = res.json().await
            .map_err(|e| AiomeError::Infrastructure { reason: format!("Failed to parse Search API response: {}", e) })?;

        let mut trends = Vec::new();
        if let Some(web) = search_res.web {
            for item in web.results {
                if let Some(desc) = item.description {
                    let sanitized = Self::sanitize_snippet(&desc);
                    if !sanitized.is_empty() {
                        trends.push(TrendItem {
                            keyword: sanitized,
                            source: "ExternalSearch".to_string(),
                            score: 1.0, // Base score, could be dynamic
                        });
                    }
                }
            }
        }

        if trends.is_empty() {
            tracing::warn!("ExternalTrendSonar: No results found for '{}'", category);
        }

        Ok(trends)
    }
}

#[derive(Deserialize, JsonSchema)]
pub struct TrendArgs {
    pub category: String,
}

#[derive(Serialize)]
pub struct TrendOutput {
    pub trends: Vec<TrendItem>,
}

#[async_trait]
impl AgentAct for ExternalTrendSonar {
    type Input = TrendRequest;
    type Output = TrendResponse;

    async fn execute(
        &self,
        input: Self::Input,
        _jail: &bastion::fs_guard::Jail,
    ) -> Result<Self::Output, AiomeError> {
        let trends = self.get_trends(&input.category).await?;
        Ok(TrendResponse { items: trends })
    }
}
